### ISSUE TITLE
Calling Strava().oauth() throws exception.

### ISSUE THREAD

**Issue by maxgmer** [BirdyF/strava_flutter#17]
When I call oauth(), url_launcher's launch() method throws exception:

E/MethodChannel#plugins.flutter.io/url_launcher( 5495): android.content.ActivityNotFoundException: Unable to find explicit activity class {com.mypackage.myapp/io.flutter.plugins.urllauncher.WebViewActivity}; have you declared this activity in your AndroidManifest.xml?

Tried to declare the necessary activity, didn't help. The strange thing is that url_launcher has the required activity in AndroidManifest.xml, so exception should not be thrown.

**Comment by BirdyF** [comment]
Hi @maxgmer,

I will look at it. Which Android version are you using?

**Comment by maxgmer** [comment]
@BirdyF Thanks! I'm using Android 8.1

**Comment by BirdyF** [comment]
I tested quickly on Android 9 using https://github.com/BirdyF/rw_tcx to test the package strava_flutter and I dont have the exception.
I will test later on Android 8 (dont have 8.1). 
Could you check if you have the same problem when running rw_tcx example (only the strava auth at the beginning)?

**Comment by maxgmer** [comment]
I resolved the issue, sorry for creating it there, it wasn't connected to the library at all. I just opened android module of the flutter project from Android Studio and Android Studio downloaded something while building the project, then I returned back to flutter project and everything worked xD
