### ISSUE TITLE
uploadActivity 'Token not yet known'

### ISSUE THREAD

**Issue by David-Hughes3** [BirdyF/strava_flutter#24]
Hello,
I appreciate the work done on this library, and it has worked well for my class project so far.

I encountered this Fault error message today 'Token not yet known', when using uploadActivity(...). I had to change the verification of the header below for it to work. I believe this issue was added in commit 39adf926e738040c2d1a4fe7933c14f4cbfb1f92.

In 'strava_flutter/lib/globals.dart' on line 31-35
```
      if (_token.accessToken != null) { 
        return {'Authorization': 'Bearer ${_token.accessToken}'}; 
      } else { 
        return {'88': '00'}; 
      }
```

In 'strava_flutter/lib/API/upload.dart' on line 50-56
```
var _header = globals.createHeader();

      if (_header.containsKey('88') == false) {
      globals.displayInfo('Token not yet known');
      fault = Fault(error.statusTokenNotKnownYet, 'Token not yet known');
      return fault;
    }
```
Line 52 should be

 **if (_header.containsKey('88') == true){**

I believe the logic for the other changed statements in commit 39adf926e738040c2d1a4fe7933c14f4cbfb1f92 were correct, I think it was just this one.

Thanks again for creating this package

**Comment by BirdyF** [comment]
Hi @David-Hughes3 ,

Thanks for bringing this problem. 
I agree with you. I will do some tests later today and will push a new release.

**Comment by BirdyF** [comment]
Hi @David-Hughes3 

I pushed a new version (1.2.0+46) fixing the problem.
Thanks for contributing/
