### ISSUE TITLE
startDate and startDateLocal removed from SummaryActivity

### ISSUE THREAD

**Issue by heymonkeyriot** [BirdyF/strava_flutter#25]
Hi,
Thanks for all the work on this package! 

Upgrading from v.1.1.0 to 1.2.0 I encountered an issue with startDate and startDateLocal being commented out of the SummaryActivity model. 

It looks like it was from the PR relating to #24 where they ended up being commented out but can't see why they would have created an issue. At the moment I'm simply running it as a local package with those lines commented out but would rather use the pub.dev version in pubspec.

Is there an error being thrown by having these fields somewhere else that I'm not aware of? Or is it safe for them to be uncommented?

**Comment by BirdyF** [comment]
Hi @heymonkeyriot 

Thanks for bringing this problem.
I will look at it tomorrow and will answer you.

**Comment by BirdyF** [comment]
Hi @heymonkeyriot 
I pushed a new version (1.2.0+47) where I test if json['start_date'] is null because when running some tests I found some activities with start_date at null.
Let me know if it is OK for you.

**Comment by heymonkeyriot** [comment]
Thanks so much @BirdyF for getting that updated so quickly. I'll go and test early tomorrow and let you know.

**Comment by heymonkeyriot** [comment]
All working as expected for me 👍
