### ISSUE TITLE
Infinite Loop in getLoggedInAthleteActivities

### ISSUE THREAD

**Issue by etabakov** [BirdyF/strava_flutter#26]
**Steps to reproduce:**

1. Create oauth token without the activity:read_all
2. Call getLoggedInAthleteActivities, parameters don't matter

**Expected Behavior:**
The method returns an error about insufficient permissions or whatever the Strava API will return.

**Actual Behavior:**
The method gets in infinite loop. As a result, you really quickly hit the API Rate limit and you cannot use the API for the next 15 minutes. 

Take a loot at this loop, it will be ended only if the returned statusCode is 200:
https://github.com/BirdyF/strava_flutter/blob/272f116e708979ef0dabb0c331c3e5d4e5de378c/lib/API/athletes.dart#L191-L233

**Comment by BirdyF** [comment]
Hi @etabakov 
Thanks for pointing this error!
I think that isRetrieveDone = true is missing when error code is not 200.
I will look at it today and will push a new release or if you prefer you can do a PR.

**Comment by etabakov** [comment]
Thanks for the quick reply! I'm still new to Flutter, but I will be happy to give it a shot with this PR.

**Comment by BirdyF** [comment]
Dont worry I am new too! 
You can do a PR and I will test it today if you like.

**Comment by BirdyF** [comment]
Hi @etabakov 
I pushed a new version (1.2.0+48) that should fix the problem.
I added a special button ("permissions") in the example to test so you can test .
Let me know if it is OK for you.

**Comment by etabakov** [comment]
Yes, the problem is resolved. Thanks a lot for the quick turnaround!
