### ISSUE TITLE
Get id of club members

### ISSUE THREAD

**Issue by kaciula** [BirdyF/strava_flutter#28]
Thanks for the package. It helped me bootstrap my app.

My specific use case is to group club activities made by each member of a club. But I see that getClubMembersById() does not include the id of the member. Furthermore, getClubActivitiesById() returns a list of SummaryActivity objects which contain an athlete object but with a null id.

Any suggestion on how I can achieve what I want? I can also start working on a pull request but first I need to know if the Strava API can give me what I want. Maybe I have to be a club administrator to get back the ids of the members?

**Comment by BirdyF** [comment]
Hi @kaciula 

I will do some tests and will let you know.

**Comment by BirdyF** [comment]
Strange, I dont see how it is possible (but I am not using Athlete API).
SummaryAthlete has id but getClubMembersById() does not return the id members, based on my tests and Strava developers docs (sample response to getClubMembersById()).

I tried with the club Marseille that I am member and get the same result.
I pushed a new version (1.2.0+49) where I added id in SummaryAthlete class so you can try if you a club  administrator.
Maybe you should ask also the question to strava-api@googlegroups.com.
I am curious to know if it is possible
Let me know if I can be of any help.

**Comment by kaciula** [comment]
@BirdyF Unfortunately, it is not possible to get data for other club members, even if you are the admin. The Strava club API is right now useless.

https://groups.google.com/forum/#!topic/strava-api/fTTkp_FmoFU

Thanks for the support.
