### ISSUE TITLE
GetActivityId might return double as totalElevationGain

### ISSUE THREAD

**Issue by etabakov** [BirdyF/strava_flutter#29]
Using getAcitvityId over some activities throw an error "type 'double' is not a subtype of type 'int' ". In this particular case the value returned from Strava API for totalElevationGain is 28.0.

**Comment by BirdyF** [comment]
Thanks contributing.
I added .toDouble() in totalElevationGain = json['total_elevation_gain'].toDouble();
in case others app put an integer in this property.

**Comment by etabakov** [comment]
Yeah, good point!
