### ISSUE TITLE
getActivityById errors when creating DetailedActivity object

### ISSUE THREAD

**Issue by ajgreenman** [BirdyF/strava_flutter#37]
When calling getActivityById(id) with a valid Id, I am returned a 200 response but the DetailedActivity.fromJson call errors with an unhandled exception. See stack trace with Strava client in debug mode:

`I/flutter ( 4710): --> Strava_flutter: Entering getActivityById`
`I/flutter ( 4710): --> Strava_flutter: 200`
`I/flutter ( 4710): --> Strava_flutter: Activity info {"resource_state":3,"athlete":{"id":9999999,"resource_state":1},"name":"Neighborhood Recovery","distance":truncated json....`
`E/flutter ( 4710): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: type 'double' is not a subtype of type 'int'`
`E/flutter ( 4710): #0      new DetailedActivity.fromJson 
package:strava_flutter/Models/activity.dart:198`
`E/flutter ( 4710): #1      Activities.getActivityById 
package:strava_flutter/API/activities.dart:34`
`E/flutter ( 4710): <asynchronous suspension>`

It seems like something in the json is resolving as a double and trying to be stored as an int. I will investigate the DetailedActivity coode and comment if I find something but I wanted to get this issue created and visible.

**Comment by ajgreenman** [comment]
I believe the issue might be with suffer_score. It is an int in the model but in the API is being returned as a double. Later today I will see about submitting a PR

**Comment by BirdyF** [comment]
Thanks for the PR
