### ISSUE TITLE
How to get the list of gears of an athlete without knowing the id of any gear(getGearById(someId)) 

### ISSUE THREAD

**Issue by blaze021** [BirdyF/strava_flutter#40]

**Comment by BirdyF** [comment]
I think that you can get the id of a gear in the answer of getLoggedInAthlete
[getLoggedInAthlete](https://developers.strava.com/docs/reference/#api-Athletes-getLoggedInAthlete)

For instance like in the example of the strava API documentation 
"bikes" : [ {
    "id" : "b12345678987655",
    "primary" : true,
    "name" : "EMC",
    "resource_state" : 2,
    "distance" : 0
  } ],
  "shoes" : [ {
    "id" : "g12345678987655",
    "primary" : true,
    "name" : "adidas",
    "resource_state" : 2,
    "distance" : 4904
  } ]

**Comment by blaze021** [comment]
Thank you!
