### ISSUE TITLE
Authorization with multiple users

### ISSUE THREAD

**Issue by haslinger** [BirdyF/strava_flutter#41]
I realize, that this might be an odd use case, but it would be awesome to log out and log in as a different user.

I guess this should be possible right now, by removing the 4 values from prefs and globals for one user, and stick the old ones from the other user in, so feel free to close this issue immediately. But it would be really nice to have it in the api directly.

**Comment by BirdyF** [comment]
Hi Stefan,
Have you tried deauthorize()?

**Comment by haslinger** [comment]
Completely missed that! Will try immediately. Thanks!

**Comment by haslinger** [comment]
deauthorize() invalidates the token, but with the next request the authorization is not retriggerd, log says, that response is not 200 but 401. And actually I don't want to devalidate, just swap between the users. So I stayed with swapping in and out the four values from prefs and globals. That totally does the trick for me.

It somebody else want to do something similarly, here is my code: https://github.com/3schweinehunde/encrateia/blob/master/lib/models/strava_token.dart
