### ISSUE TITLE
Token null related checks and clauses seem to be off

### ISSUE THREAD

**Issue by MrCsabaToth** [BirdyF/strava_flutter#47]
I'll test some of the changes in my copy of the code.

**Comment by MrCsabaToth** [comment]
These changes are very dangerous and if not correct they could break the login or the token renewal procedure.

**Comment by BirdyF** [comment]
Hi @MrCsabaToth 

Thanks for contributing!
I agree with your changes.
Let me know if you see any problem when testing. If it is the case I will revert.
