### ISSUE TITLE
Preference keys should not use generic names

### ISSUE THREAD

**Issue by WolfMoestl** [BirdyF/strava_flutter#5]
In the current Version 1.09 the Strava token information is stored as pereferencs using names like    'accessToken', 'expire', 'scope', 'refreshToken'. 

These names are quite common ones, they can easily interfere with preferences of other libraraies or the ones of the application.

An easy way would of avoiding this would be to prefix the names with a library shortcut.
E.g.: 'strava_accessToken', 'strava_expire', 'strava_scope', 'strava_refreshToken'.

**Comment by BirdyF** [comment]
Thanks for your feedback. 
It is useful for me.

I will follow your advice and update the preference keys in the next few days.

**Comment by BirdyF** [comment]
I pushed a new version (1.0.11+25) with added prefix "strava_" in preference keys.
