### ISSUE TITLE
Missing variable assignment

### ISSUE THREAD

**Issue by e385** [BirdyF/strava_flutter#50]
In class RefreshAnswer (token.dart) the value for ` model.expiresIn` isn't assigned:

`    model.expiresAt = map['expires_in'];`
should be
`    model.expiresIn = map['expires_in'];`

**Comment by BirdyF** [comment]
Hi @e385 
Thanks. Could you do a PR please?

**Comment by e385** [comment]
Hi @BirdyF , done✅
